version: "3.3"
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:

  dashboard:
    image: ghcr.io/oakestra/dashboard:latest
    ports:
      - '80:80'
    restart: unless-stopped
    container_name: oaekstra-frontend-container
    environment:
      - API_ADDRESS=${SYSTEM_MANAGER_URL}:10000

  # System Manager REST API of Root Orchestrator
  system_manager:
    image: ghcr.io/jakobke/oakestra-root-grpc:1.5 #ghcr.io/oakestra/oakestra/root-system-manager:latest
    hostname: system_manager
    container_name: system_manager
    labels:
      logging: "promtail"
      logging_jobname: "rootlogs"
    expose:
      - "10000"
      - "50052"
    ports:
      - "50052:50052"
      - "10000:10000"
    depends_on:
      - mongo_root
      - cloud_scheduler
      - root_service_manager
    environment:
      - CLOUD_MONGO_URL=mongo
      - CLOUD_MONGO_PORT=10007
      - CLOUD_SCHEDULER_URL=cloud_scheduler
      - CLOUD_SCHEDULER_PORT=10004
      - NET_PLUGIN_URL=root_service_manager
      - NET_PLUGIN_PORT=10099


  # cluster-level mongoDB
  mongo_rootnet:
    image: mongo:3.6
    container_name: mongo_net
    hostname: mongo_net
    labels:
      logging: "promtail"
    expose:
      - "10008"
    volumes:
      - 'mongodb_net_data:/mongodb'
    command: mongod --port 10008
    logging: *default-logging

  # MongoDB in Root Orchestrator
  mongo_root:
    image: mongo:3.6
    container_name: mongo
    hostname: mongo
    expose:
      - "10007"
    volumes:
      - 'mongodb_data:/mongodb'
    command: mongod --port 10007

  # Cluster Manager
  root_service_manager:
    image: ghcr.io/oakestra/oakestra-net/root-service-manager:v0.4.301
    container_name: root_service_manager
    hostname: root_service_manager
    labels:
      logging: "promtail"
      logging_jobname: "rootlogs"
    expose:
      - "10099"
    ports:
      - "10099:10099"
    environment:
      - MY_PORT=10099
      - SYSTEM_MANAGER_URL=system_manager
      - SYSTEM_MANAGER_PORT=10000
      - CLOUD_MONGO_URL=mongo_net
      - CLOUD_MONGO_PORT=10008
    depends_on:
      - mongo_rootnet
    logging: *default-logging


  # Redis for the Cloud Scheduler
  redis:
    image: redis
    hostname: redis
    container_name: redis
    expose:
      - "6379"
    command: redis-server --requirepass cloudRedis

  resource_abstractor:
    image: ghcr.io/jakobke/oakestra/resource-abstractor:1.1 #ghcr.io/oakestra/oakestra/root-resource-abstractor:latest
    container_name: resource_abstractor
    hostname: resource_abstractor
    labels:
      logging: "promtail"
      logging_jobname: "rootlogs"
    expose:
      - "11011"
    ports:
      - "11011:11011"
    environment:
      - RESOURCE_ABSTRACTOR_PORT=11011
      - CLOUD_MONGO_URL=mongo
      - CLOUD_MONGO_PORT=10007
    depends_on:
      - mongo_root
    logging: *default-logging


  # Cloud Scheduler
  cloud_scheduler:
    image: ghcr.io/oakestra/oakestra/cloud-scheduler:v0.4.301
    container_name: cloud_scheduler
    hostname: cloud_scheduler
    labels:
      logging: "promtail"
      logging_jobname: "rootlogs"
    expose:
      - "10004"
    environment:
      - MY_PORT=10004
      - SYSTEM_MANAGER_URL=system_manager
      - SYSTEM_MANAGER_PORT=10000
      - RESOURCE_ABSTRACTOR_URL=resource_abstractor
      - RESOURCE_ABSTRACTOR_PORT=11011
      - REDIS_ADDR=redis://:cloudRedis@redis:6379
      - CLOUD_MONGO_URL=mongo #adding this for consistency with version 0.4.300
      - CLOUD_MONGO_PORT=10007 #adding this for consistency with version 0.4.300
    depends_on:
      - redis
      - resource_abstractor
    logging: *default-logging



volumes:
  mongodb_data:
    driver: local
  mongodb_cluster_data:
    driver: local
  mongodb_cluster_net_data:
    driver: local
  mongodb_net_data:
    driver: local

networks:
  ip6net:
    enable_ipv6: true
